name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Prepare Dockerfile
      run: cp ./docker/Dockerfile.admin ./Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_ADMIN_USERNAME }}
        password: ${{ secrets.DOCKER_ADMIN_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_ADMIN_USERNAME }}/ecommerceapp:latest

    - name: Verify Pushed Image
      run: docker pull ${{ secrets.DOCKER_ADMIN_USERNAME }}/ecommerceapp:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_ADMIN_USERNAME }}/ecommerceapp:latest
          sudo docker stop ecommerce-server || true
          sudo docker rm ecommerce-server || true
          sudo docker run -d --name ecommerce-server -p 3001:3001 -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e SALT=${{ secrets.SALT }} -e USER_EMAIL=${{ secrets.USER_EMAIL }} -e USER_EMAIL_PASSWORD=${{ secrets.USER_EMAIL_PASSWORD }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e ADMIN_CLIENT_URL=${{ secrets.ADMIN_CLIENT_URL }}  ${{ secrets.DOCKER_ADMIN_USERNAME }}/ecommerceapp:latest
    
    